<a href="https://colab.research.google.com/github/MatthewArk123/spatial_programming_sketches/blob/main/sketch04_arkwright.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# The code below tells Collab to run an install rather than a code and installs all of the needed libaries
%pip install -q libpysal esda splot mapclassify contextily
# I can also get rid of the -q and run it as %pip install -q libpysal esda splot mapclassify contextily
# In doing this I will see the step by step progress of my downloads but it will be very long and is not necessarily needed


# The code below tells Colab where to pull the data from and/or where im working (its like a workspace but on the internet/cloud)
# Its good to always use the raw url as a simple copy and pasted URL makes Colab/Python run it as a link and not data (this was an error I experienced)
DATA_LOCATION = "https://raw.githubusercontent.com/pjbitterman/KSU_x9076/main/data"

In [40]:
# geopandas does not need to be gpd but this code imports geopandas which is a libary for dealing with spatial data
# Same goes for pandas reading as pd
# geopandas is better suited for spatial data and pandas is better suited for data in tables like a csv file
# Therefore I am commenting out importing geopandas and instead am importing pandas


### import geopandas as gpd ###
import pandas as pd


# The code below imports ohio_precip_2025.csv from the data in Dr. Bittermans repository
# I could load the data into my own and work from there but that requires downloading that is not really necessary
precip = pd.read_csv(f"{DATA_LOCATION}/part1/ohio_precip_2025.csv")

# For the code below the last code is automatically printed on the output section (hence .describe showing up) to get the table showing the column names (using .head) to also show I needed to wrap it in a print
# Length tells me how many stations there are
# .head lists the first 5 of those stations in the list as well as their column names
# .describe lists the statistical info about the data in the file

# Using display instead of print allows me to make tables I can actually hover over rather than smaller print that is just an output
print(f"There are {len(precip)} precipitation stations in Ohio.")
precip.head()
display (precip.head())
precip["precip_mm_2025"].describe()
display (precip["precip_mm_2025"].describe())


# Using the parameters feature in Google Colab I was able to figure out the parameters needed to sort the 5 stations with the 5 highest precip values
# Setting ascedning to False tells Python to sort through the list with the parameter of "precip_mm_2025" and sort it from largest to smallest
# Setting ascending to True (the default) tells Python to sort the list items from least to greatest
# Using .head(5) give the top 5 stations

# I put both name and precip_mm_2025 into the double brackets to get two columns as the output/print
wettest = precip.sort_values("precip_mm_2025", ascending=False).head(5)
display (wettest[["name", "precip_mm_2025"]])

max_precip = precip["precip_mm_2025"].max()
mean_precip = precip["precip_mm_2025"].mean()

difference = max_precip - mean_precip

print(f"The station precip mean is {mean_precip:.2f}mm with the max precip recorded meaning {max_precip}mm. Therefore the station with the max precip recorded was {difference:.2f}mm over the mean.")

There are 410 precipitation stations in Ohio.

    station_id               name      lat      lon  precip_mm_2025
0  US1OHAB0021  ASHTABULA 1.8 NNE  41.9037 -80.7829           910.4
1  US1OHAD0005       SEAMAN 3.4 E  38.9399 -83.5090          1270.7
2  US1OHAD0006      PEEBLES 4.2 N  39.0075 -83.4146          1174.8
3  US1OHAL0005        LIMA 2.7 NE  40.7739 -84.0800           904.3
4  US1OHAL0008    DELPHOS 2.3 ESE  40.8335 -84.2982           711.4

count     410.000000
mean     1008.862439
std       174.937689
min       350.900000
25%       895.575000
50%      1014.050000
75%      1125.500000
max      1495.700000
Name: precip_mm_2025, dtype: float64

                              name  precip_mm_2025
406  CINCINNATI MUNI AP LUNKEN FLD          1495.7
228                 SHELBY 0.6 NNE          1488.7
16                  ATHENS 4.6 ESE          1431.6
108             MIDDLEFIELD 0.6 NE          1411.7
48                   MIDLAND 2.9 S          1402.5

The station precip mean is 1008.86mm with the max precip recorded meaning 1495.7mm. Therefore the station with the max precip recorded was 486.84mm over the mean.

The station with the max precip readings was 486.84mm over the mean which is not really suprising. The stations that we used are from 2025 and cover all of those in Ohio, therefore, one area of Ohio may have gotten more precipitation than another area that is typically more dry. The weather is a weird thing and sometimes some areas get substantially more rain, weather events, etc. than other areas.